[target.thumbv6m-none-eabi]
runner = "probe-rs run --chip PY32F003x4"
rustflags = [
  "-C",
  "link-arg=-Tlink.x",
  "-C",
  "link-arg=--nmagic",

  # --- Defmt link script ---
  "-C",
  "link-arg=-Tdefmt.x",
]

[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "trace"
